### ISSUE TITLE
[Use-case] Google News Scraper for Major Company News

### ISSUE THREAD

**Issue by dnlkwak** [monkey-patch-sdk/monkey-patch.py#45]
* Workflow
	* Scrape https://news.google.com/search?q=nvidia&hl=en-US&gl=US&ceid=US%3Aen every 3 hours
	* Extract:
		* Impact to the company: (0 - if nothing, 10 if major)
		* Sentiment: (-1 to 1)
		* Date
		* Companies involved:
		* People involved:
		* 2-line summary:
		* Location:
	* If over 5 on importance and lower than 0 on sentiment => email to: dexter+invest@gmail.com

**Comment by JackHopkins** [comment]
https://github.com/monkey-patch-sdk/monkey-patch.py/pull/53
